# Generated by Django 3.1.3 on 2022-07-08 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('EEE', 'EEE'), ('CE', 'CE'), ('BECM', 'BECM'), ('Arch', 'Arch'), ('URP', 'URP'), ('ME', 'ME'), ('IPE', 'IPE'), ('GCE', 'GCE'), ('MTE', 'MTE'), ('MSE', 'MSE'), ('CFPE', 'CFPE'), ('Chem', 'Chem'), ('Math', 'Math'), ('Phy', 'Phy'), ('Hum', 'Hum')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 8, 6, 2, 3, 736324, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('EEE', 'EEE'), ('CE', 'CE'), ('BECM', 'BECM'), ('Arch', 'Arch'), ('URP', 'URP'), ('ME', 'ME'), ('IPE', 'IPE'), ('GCE', 'GCE'), ('MTE', 'MTE'), ('MSE', 'MSE'), ('CFPE', 'CFPE'), ('Chem', 'Chem'), ('Math', 'Math'), ('Phy', 'Phy'), ('Hum', 'Hum')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.BigIntegerField(default=880),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Professor ', 'Professor '), ('Assistant Professor ', 'Assistant Professor '), ('Head Master', 'Head Master')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classReadin',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('Masters', 'Masters')], max_length=7),
        ),
    ]
