# Generated by Django 3.1.3 on 2022-07-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220708_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classReadin',
            new_name='year',
        ),
    ]
