# Generated by Django 3.1.3 on 2022-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220708_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ETE', 'ETE'), ('EEE', 'EEE'), ('CE', 'CE'), ('BECM', 'BECM'), ('Arch', 'Arch'), ('URP', 'URP'), ('ME', 'ME'), ('IPE', 'IPE'), ('GCE', 'GCE'), ('MTE', 'MTE'), ('MSE', 'MSE'), ('CFPE', 'CFPE'), ('Chem', 'Chem'), ('Math', 'Math'), ('Phy', 'Phy'), ('Hum', 'Hum')], default='CSE', max_length=5),
        ),
    ]
