# Generated by Django 3.1.3 on 2022-07-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='descrioption',
            new_name='description',
        ),
    ]
