# Generated by Django 3.1.3 on 2022-07-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220708_1243'),
        ('app', '0003_auto_20220708_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='profiles.Student'),
        ),
        migrations.AddField(
            model_name='complain',
            name='same',
            field=models.ManyToManyField(blank=True, default=None, related_name='same', to='profiles.Student'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
