# Generated by Django 3.1.3 on 2022-07-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220708_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='status',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Submitted', 'Submitted'), ('Checking', 'Checking'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Submitted', max_length=10)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.complain')),
            ],
        ),
    ]
