# Generated by Django 3.1.3 on 2022-07-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220708_1243'),
        ('app', '0005_auto_20220708_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complain',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CommentByTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.teacher')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
