# Generated by Django 3.1.3 on 2022-07-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220712_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='last_updated',
        ),
    ]
